DROP TABLE IF EXISTS usuario_log;

/*
CREATE TABLE usuario_log (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,   
  id_usuario INT(10) UNSIGNED DEFAULT NULL,
  datahora DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_usuario_log PRIMARY KEY (id),
  CONSTRAINT fk_usuario_log_1 FOREIGN KEY (id_usuario) REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE CASCADE
);
*/



